apiVersion: v1
data:
  nginx.conf: |
    events {
    }
    http {
      server {
        listen 80;
        location / {
          root /usr/share/nginx/html;
          index index.html;
        }
      }
    }
kind: ConfigMap
metadata:
  name: nginx-config
