name: Close inactive issues
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: 30
          days-before-issue-close: 14
          stale-issue-label: "stale"
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had
            activity in the 30 days. It will be closed in 14 days if no further activity occurs. Please
            feel free to leave a comment if you believe the issue is still relevant.
            Thank you for your contributions!
          close-issue-message: >
            This issue has been automatically closed because it has not had any further
            activity in the last 14 days. Thank you for your contributions!
          days-before-pr-stale: 60
          days-before-pr-close: 14
          stale-pr-label: "stale"
          stale-pr-message: >
            This pull request has been automatically marked as stale because it has not had
            activity in the last 60 days. It will be closed in 14 days if no further activity occurs. Please
            feel free to give a status update or ping for review. Thank you for your contributions!
          close-pr-message: >
            This pull request has been automatically closed because it has not had any further
            activity in the last 14 days. Thank you for your contributions!
          repo-token: ${{ secrets.GITHUB_TOKEN }}